# Generated by Django 4.0 on 2021-12-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('content', models.TextField(max_length=500)),
                ('image', models.URLField(max_length=500, null=True)),
                ('user', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'posts',
            },
        ),
    ]
